const WORDS = {
  "pork": {
    category: "food",
    isSubstance: true,
    isFood: true,
    isDrink: false,
    isFinancial: false,
    isSpeech: false,
    isWorship: false,
    isEntertainment: false,
    isBodyRelated: false,
    isAnimal: true,
    isIntoxicant: false,
    isPhysicalObject: true,
    isAction: false,
    isAbstract: false,
    isConsumed: true,
    hint: "a type of meat"
  },
  "alcohol": {
    category: "food",
    isSubstance: true,
    isFood: false,
    isDrink: true,
    isFinancial: false,
    isSpeech: false,
    isWorship: false,
    isEntertainment: false,
    isBodyRelated: false,
    isAnimal: false,
    isIntoxicant: true,
    isPhysicalObject: true,
    isAction: false,
    isAbstract: false,
    isConsumed: true,
    hint: "a liquid substance"
  },
  "drugs": {
    category: "food",
    isSubstance: true,
    isFood: false,
    isDrink: false,
    isFinancial: false,
    isSpeech: false,
    isWorship: false,
    isEntertainment: false,
    isBodyRelated: false,
    isAnimal: false,
    isIntoxicant: true,
    isPhysicalObject: true,
    isAction: false,
    isAbstract: false,
    isConsumed: true,
    hint: "a substance"
  },
  "blood": {
    category: "food",
    isSubstance: true,
    isFood: false,
    isDrink: false,
    isFinancial: false,
    isSpeech: false,
    isWorship: false,
    isEntertainment: false,
    isBodyRelated: true,
    isAnimal: false,
    isIntoxicant: false,
    isPhysicalObject: true,
    isAction: false,
    isAbstract: false,
    isConsumed: true,
    hint: "a bodily liquid"
  },
  "carrion": {
    category: "food",
    isSubstance: true,
    isFood: true,
    isDrink: false,
    isFinancial: false,
    isSpeech: false,
    isWorship: false,
    isEntertainment: false,
    isBodyRelated: false,
    isAnimal: true,
    isIntoxicant: false,
    isPhysicalObject: true,
    isAction: false,
    isAbstract: false,
    isConsumed: true,
    hint: "dead animal flesh"
  },
  "donkey meat": {
    category: "food",
    isSubstance: true,
    isFood: true,
    isDrink: false,
    isFinancial: false,
    isSpeech: false,
    isWorship: false,
    isEntertainment: false,
    isBodyRelated: false,
    isAnimal: true,
    isIntoxicant: false,
    isPhysicalObject: true,
    isAction: false,
    isAbstract: false,
    isConsumed: true,
    hint: "a type of meat"
  },
  "riba": {
    category: "financial",
    isSubstance: false,
    isFood: false,
    isDrink: false,
    isFinancial: true,
    isSpeech: false,
    isWorship: false,
    isEntertainment: false,
    isBodyRelated: false,
    isAnimal: false,
    isIntoxicant: false,
    isPhysicalObject: false,
    isAction: true,
    isAbstract: true,
    isConsumed: false,
    hint: "a financial concept"
  },
  "gambling": {
    category: "financial",
    isSubstance: false,
    isFood: false,
    isDrink: false,
    isFinancial: true,
    isSpeech: false,
    isWorship: false,
    isEntertainment: true,
    isBodyRelated: false,
    isAnimal: false,
    isIntoxicant: false,
    isPhysicalObject: false,
    isAction: true,
    isAbstract: false,
    isConsumed: false,
    hint: "an activity involving money"
  },
  "bribery": {
    category: "financial",
    isSubstance: false,
    isFood: false,
    isDrink: false,
    isFinancial: true,
    isSpeech: false,
    isWorship: false,
    isEntertainment: false,
    isBodyRelated: false,
    isAnimal: false,
    isIntoxicant: false,
    isPhysicalObject: false,
    isAction: true,
    isAbstract: false,
    isConsumed: false,
    hint: "a corrupt action"
  },
  "fraud": {
    category: "financial",
    isSubstance: false,
    isFood: false,
    isDrink: false,
    isFinancial: true,
    isSpeech: false,
    isWorship: false,
    isEntertainment: false,
    isBodyRelated: false,
    isAnimal: false,
    isIntoxicant: false,
    isPhysicalObject: false,
    isAction: true,
    isAbstract: true,
    isConsumed: false,
    hint: "a deceptive action"
  },
  "stealing": {
    category: "financial",
    isSubstance: false,
    isFood: false,
    isDrink: false,
    isFinancial: true,
    isSpeech: false,
    isWorship: false,
    isEntertainment: false,
    isBodyRelated: false,
    isAnimal: false,
    isIntoxicant: false,
    isPhysicalObject: false,
    isAction: true,
    isAbstract: false,
    isConsumed: false,
    hint: "a criminal action"
  },
  "lying": {
    category: "speech",
    isSubstance: false,
    isFood: false,
    isDrink: false,
    isFinancial: false,
    isSpeech: true,
    isWorship: false,
    isEntertainment: false,
    isBodyRelated: false,
    isAnimal: false,
    isIntoxicant: false,
    isPhysicalObject: false,
    isAction: true,
    isAbstract: false,
    isConsumed: false,
    hint: "something done with words"
  },
  "backbiting": {
    category: "speech",
    isSubstance: false,
    isFood: false,
    isDrink: false,
    isFinancial: false,
    isSpeech: true,
    isWorship: false,
    isEntertainment: false,
    isBodyRelated: false,
    isAnimal: false,
    isIntoxicant: false,
    isPhysicalObject: false,
    isAction: true,
    isAbstract: false,
    isConsumed: false,
    hint: "talking about others"
  },
  "slander": {
    category: "speech",
    isSubstance: false,
    isFood: false,
    isDrink: false,
    isFinancial: false,
    isSpeech: true,
    isWorship: false,
    isEntertainment: false,
    isBodyRelated: false,
    isAnimal: false,
    isIntoxicant: false,
    isPhysicalObject: false,
    isAction: true,
    isAbstract: true,
    isConsumed: false,
    hint: "false speech about others"
  },
  "arrogance": {
    category: "speech",
    isSubstance: false,
    isFood: false,
    isDrink: false,
    isFinancial: false,
    isSpeech: true,
    isWorship: false,
    isEntertainment: false,
    isBodyRelated: false,
    isAnimal: false,
    isIntoxicant: false,
    isPhysicalObject: false,
    isAction: false,
    isAbstract: true,
    isConsumed: false,
    hint: "a character trait"
  },
  "shirk": {
    category: "worship",
    isSubstance: false,
    isFood: false,
    isDrink: false,
    isFinancial: false,
    isSpeech: false,
    isWorship: true,
    isEntertainment: false,
    isBodyRelated: false,
    isAnimal: false,
    isIntoxicant: false,
    isPhysicalObject: false,
    isAction: true,
    isAbstract: true,
    isConsumed: false,
    hint: "the gravest sin in Islam"
  },
  "black magic": {
    category: "worship",
    isSubstance: false,
    isFood: false,
    isDrink: false,
    isFinancial: false,
    isSpeech: false,
    isWorship: true,
    isEntertainment: false,
    isBodyRelated: false,
    isAnimal: false,
    isIntoxicant: false,
    isPhysicalObject: false,
    isAction: true,
    isAbstract: false,
    isConsumed: false,
    hint: "a supernatural practice"
  },
  "astrology": {
    category: "worship",
    isSubstance: false,
    isFood: false,
    isDrink: false,
    isFinancial: false,
    isSpeech: false,
    isWorship: true,
    isEntertainment: true,
    isBodyRelated: false,
    isAnimal: false,
    isIntoxicant: false,
    isPhysicalObject: false,
    isAction: false,
    isAbstract: true,
    isConsumed: false,
    hint: "involves stars and horoscopes"
  },
  "fortune telling": {
    category: "worship",
    isSubstance: false,
    isFood: false,
    isDrink: false,
    isFinancial: false,
    isSpeech: false,
    isWorship: true,
    isEntertainment: false,
    isBodyRelated: false,
    isAnimal: false,
    isIntoxicant: false,
    isPhysicalObject: false,
    isAction: true,
    isAbstract: false,
    isConsumed: false,
    hint: "predicting the future"
  },
  "pornography": {
    category: "entertainment",
    isSubstance: false,
    isFood: false,
    isDrink: false,
    isFinancial: false,
    isSpeech: false,
    isWorship: false,
    isEntertainment: true,
    isBodyRelated: true,
    isAnimal: false,
    isIntoxicant: false,
    isPhysicalObject: false,
    isAction: false,
    isAbstract: true,
    isConsumed: false,
    hint: "explicit content"
  },
  "animal fighting": {
    category: "entertainment",
    isSubstance: false,
    isFood: false,
    isDrink: false,
    isFinancial: false,
    isSpeech: false,
    isWorship: false,
    isEntertainment: true,
    isBodyRelated: false,
    isAnimal: true,
    isIntoxicant: false,
    isPhysicalObject: false,
    isAction: true,
    isAbstract: false,
    isConsumed: false,
    hint: "involves animals"
  },
  "tattoos": {
    category: "body",
    isSubstance: false,
    isFood: false,
    isDrink: false,
    isFinancial: false,
    isSpeech: false,
    isWorship: false,
    isEntertainment: false,
    isBodyRelated: true,
    isAnimal: false,
    isIntoxicant: false,
    isPhysicalObject: false,
    isAction: false,
    isAbstract: false,
    isConsumed: false,
    hint: "body modification"
  },
  "silk": {
    category: "body",
    isSubstance: true,
    isFood: false,
    isDrink: false,
    isFinancial: false,
    isSpeech: false,
    isWorship: false,
    isEntertainment: false,
    isBodyRelated: true,
    isAnimal: true,
    isIntoxicant: false,
    isPhysicalObject: true,
    isAction: false,
    isAbstract: false,
    isConsumed: false,
    hint: "a fabric"
  },
  "gold": {
    category: "body",
    isSubstance: true,
    isFood: false,
    isDrink: false,
    isFinancial: false,
    isSpeech: false,
    isWorship: false,
    isEntertainment: false,
    isBodyRelated: true,
    isAnimal: false,
    isIntoxicant: false,
    isPhysicalObject: true,
    isAction: false,
    isAbstract: false,
    isConsumed: false,
    hint: "a precious metal"
  }
};

const WORD_LIST = Object.keys(WORDS);

module.exports = { WORDS, WORD_LIST };
